import type { Customer, Contact, Case, CaseNote, FollowUp, PicUser, User, CaseFile, ActivityLog, SettingsItem } from './types'

export const mockPics: PicUser[] = [
  { id: 'pic1', name: 'Ahmad Farid', email: 'ahmad@bondinsurance.com' },
  { id: 'pic2', name: 'Nurul Ain', email: 'nurul@bondinsurance.com' },
  { id: 'pic3', name: 'David Lim', email: 'david@bondinsurance.com' },
]

export const mockCustomers: Customer[] = [
  {
    id: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    companyRegistrationNo: '199801012345',
    industry: 'Construction',
    mainPhone: '03-12345678',
    mainEmail: 'admin@binaperkasa.com',
    notes: 'Key client. Handles large government construction projects.',
    createdAt: '2025-06-10T08:00:00Z',
  },
  {
    id: 'cust2',
    customerName: 'Maju Jaya Trading Sdn Bhd',
    companyRegistrationNo: '200201054321',
    industry: 'Trading',
    mainPhone: '03-78912345',
    mainEmail: 'admin@majujaya.com',
    notes: 'Import and export trader. Requires customs bonds every year.',
    createdAt: '2025-08-20T09:00:00Z',
  },
  {
    id: 'cust3',
    customerName: 'Teknologi Canggih Sdn Bhd',
    companyRegistrationNo: '201501098765',
    industry: 'Technology',
    mainPhone: '03-23456789',
    mainEmail: 'admin@tekcanggih.com',
    notes: 'IT company. Occasional bonds for government tenders.',
    createdAt: '2025-10-05T10:00:00Z',
  },
  {
    id: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    companyRegistrationNo: '199901076543',
    industry: 'Construction',
    mainPhone: '03-98765432',
    mainEmail: 'admin@mutiarapermai.com',
    notes: 'Property developer. Multiple bonds required per project.',
    createdAt: '2025-11-10T11:00:00Z',
  },
  {
    id: 'cust5',
    customerName: 'Prisma Logistics Sdn Bhd',
    companyRegistrationNo: '201801033210',
    industry: 'Transportation',
    mainPhone: '03-55512345',
    mainEmail: 'admin@prismalogistics.com',
    notes: 'Freight forwarding. Needs customs bonds and workers compensation.',
    createdAt: '2026-01-15T09:00:00Z',
  },
]

export const mockContacts: Contact[] = [
  // Bina Perkasa (cust1)
  {
    id: 'con1', customerId: 'cust1', contactName: 'Razif Harun',
    role: 'Managing Director', phone: '012-3456789', email: 'razif@binaperkasa.com',
    contactType: 'Director', isPrimary: true,
  },
  {
    id: 'con2', customerId: 'cust1', contactName: 'Faridah Zain',
    role: 'Finance Manager', phone: '012-3456780', email: 'faridah@binaperkasa.com',
    contactType: 'Finance', isPrimary: false,
  },
  // Maju Jaya (cust2)
  {
    id: 'con3', customerId: 'cust2', contactName: 'Lee Chee Keong',
    role: 'Owner', phone: '016-7891234', email: 'cheekeong@majujaya.com',
    contactType: 'Owner', isPrimary: true,
  },
  {
    id: 'con4', customerId: 'cust2', contactName: 'Michelle Tan',
    role: 'Operations', phone: '016-7891235', email: 'michelle@majujaya.com',
    contactType: 'Operations', isPrimary: false,
  },
  // Teknologi Canggih (cust3)
  {
    id: 'con5', customerId: 'cust3', contactName: 'Sarah Tan',
    role: 'Operations Manager', phone: '011-23456789', email: 'sarah@tekcanggih.com',
    contactType: 'Manager', isPrimary: true,
  },
  {
    id: 'con6', customerId: 'cust3', contactName: 'James Ng',
    role: 'IT Director', phone: '011-23456780', email: 'james@tekcanggih.com',
    contactType: 'Director', isPrimary: false,
  },
  // Mutiara Permai (cust4)
  {
    id: 'con7', customerId: 'cust4', contactName: 'Hafizah Mohd',
    role: 'Director', phone: '019-9876543', email: 'hafizah@mutiarapermai.com',
    contactType: 'Director', isPrimary: true,
  },
  {
    id: 'con8', customerId: 'cust4', contactName: 'Azrul Nizam',
    role: 'Project Manager', phone: '019-9876544', email: 'azrul@mutiarapermai.com',
    contactType: 'Manager', isPrimary: false,
  },
  // Prisma Logistics (cust5)
  {
    id: 'con9', customerId: 'cust5', contactName: 'Kevin Wong',
    role: 'Managing Director', phone: '017-5551234', email: 'kevin@prismalogistics.com',
    contactType: 'Director', isPrimary: true,
  },
]

export const mockCases: Case[] = [
  {
    id: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseType: 'Bond Request',
    amount: 250000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2026-01-10T08:00:00Z',
    currentStatus: 'Confirmed',
    result: 'Won',
    closingRemarks: 'Bond issued by Allianz. Effective 1 Feb 2026.',
  },
  {
    id: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    customerId: 'cust2',
    customerName: 'Maju Jaya Trading Sdn Bhd',
    caseType: 'Renewal',
    amount: 80000,
    personInCharge: 'Nurul Ain',
    createdAt: '2026-03-14T09:00:00Z',
    currentStatus: 'Submitted',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    customerId: 'cust3',
    customerName: 'Teknologi Canggih Sdn Bhd',
    caseType: 'Bond Request',
    amount: 120000,
    personInCharge: 'David Lim',
    createdAt: '2026-04-01T10:00:00Z',
    currentStatus: 'Quoted',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseType: 'Bond Request',
    amount: 500000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2026-04-20T08:00:00Z',
    currentStatus: 'Waiting Documents',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case5',
    caseTitle: 'Fidelity Guarantee — Finance Department',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseType: 'Insurance Request',
    amount: 50000,
    personInCharge: 'Nurul Ain',
    createdAt: '2026-04-28T09:00:00Z',
    currentStatus: 'New',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case6',
    caseTitle: 'Immigration Bond — Foreign Workers Batch B',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseType: 'Bond Request',
    amount: 35000,
    personInCharge: 'David Lim',
    createdAt: '2026-05-02T10:00:00Z',
    currentStatus: 'Sent to Customer',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case7',
    caseTitle: 'Workers Compensation — Freight Team',
    customerId: 'cust5',
    customerName: 'Prisma Logistics Sdn Bhd',
    caseType: 'Insurance Request',
    amount: 15000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2026-05-08T09:00:00Z',
    currentStatus: 'New',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case8',
    caseTitle: 'Performance Bond — Coastal Highway Phase 1',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseType: 'Bond Request',
    amount: 380000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2025-09-01T08:00:00Z',
    currentStatus: 'Closed',
    result: 'Lost',
    closingRemarks: 'Client went with another agent offering a lower premium.',
  },
]

export const mockCaseNotes: CaseNote[] = [
  {
    id: 'note1',
    caseId: 'case1',
    content: 'Client confirmed they want Allianz. Proceed with bond issuance.',
    createdAt: '2026-01-22T14:00:00Z',
    createdBy: 'Ahmad Farid',
  },
  {
    id: 'note2',
    caseId: 'case1',
    content: 'Bond issued. Original document couriered to client office.',
    createdAt: '2026-02-01T11:00:00Z',
    createdBy: 'Ahmad Farid',
  },
  {
    id: 'note3',
    caseId: 'case2',
    content: 'Submitted to Customs department. Reference: CUST-2026-00412.',
    createdAt: '2026-03-28T10:30:00Z',
    createdBy: 'Nurul Ain',
  },
  {
    id: 'note4',
    caseId: 'case3',
    content: 'Quotations from 3 insurers sent to client. Waiting for their decision.',
    createdAt: '2026-04-10T11:00:00Z',
    createdBy: 'David Lim',
  },
  {
    id: 'note5',
    caseId: 'case4',
    content: 'Client has not submitted audited accounts yet. Need to follow up.',
    createdAt: '2026-05-03T09:00:00Z',
    createdBy: 'Ahmad Farid',
  },
]

export const mockFollowUps: FollowUp[] = [
  {
    id: 'fu1',
    title: 'Call client to check on customs bond approval',
    customerId: 'cust2',
    customerName: 'Maju Jaya Trading Sdn Bhd',
    caseId: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    personInCharge: 'Nurul Ain',
    dueDate: '2026-05-10',
    status: 'Open',
    createdAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'fu2',
    title: 'Collect audited accounts and company profile',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseId: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    personInCharge: 'Ahmad Farid',
    dueDate: '2026-05-05',
    status: 'Done',
    createdAt: '2026-04-28T09:00:00Z',
  },
  {
    id: 'fu3',
    title: 'Send quotation comparison to client for review',
    customerId: 'cust3',
    customerName: 'Teknologi Canggih Sdn Bhd',
    caseId: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    personInCharge: 'David Lim',
    dueDate: '2026-05-20',
    status: 'Open',
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'fu4',
    title: 'Remind client about workers list for immigration bond',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseId: 'case6',
    caseTitle: 'Immigration Bond — Foreign Workers Batch B',
    personInCharge: 'David Lim',
    dueDate: '2026-05-16',
    status: 'Open',
    createdAt: '2026-05-13T10:00:00Z',
  },
  {
    id: 'fu5',
    title: 'Prepare fidelity guarantee proposal document',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseId: 'case5',
    caseTitle: 'Fidelity Guarantee — Finance Department',
    personInCharge: 'Nurul Ain',
    dueDate: '2026-05-22',
    status: 'Open',
    createdAt: '2026-05-14T09:00:00Z',
  },
  {
    id: 'fu6',
    title: 'Submit workers compensation proposal to insurer',
    customerId: 'cust5',
    customerName: 'Prisma Logistics Sdn Bhd',
    caseId: 'case7',
    caseTitle: 'Workers Compensation — Freight Team',
    personInCharge: 'Ahmad Farid',
    dueDate: '2026-05-30',
    status: 'Open',
    createdAt: '2026-05-08T11:00:00Z',
  },
]

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'usr1',
    fullName: 'Ahmad Farid',
    email: 'ahmad@bondinsurance.com',
    password: 'password123',
    role: 'Admin',
    status: 'Active',
    createdAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'usr2',
    fullName: 'Nurul Ain',
    email: 'nurul@bondinsurance.com',
    password: 'password123',
    role: 'Staff',
    status: 'Active',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'usr3',
    fullName: 'David Lim',
    email: 'david@bondinsurance.com',
    password: 'password123',
    role: 'Staff',
    status: 'Active',
    createdAt: '2024-02-01T08:00:00Z',
  },
]

// ─── Case Files ───────────────────────────────────────────────────────────────

export const mockCaseFiles: CaseFile[] = [
  {
    id: 'file1',
    caseId: 'case1',
    fileName: 'Project_Contract_MRR2.pdf',
    fileSize: 2150000,
    fileType: 'PDF',
    documentType: 'Contract',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-01-12T10:00:00Z',
    aiScanned: true,
    aiStatus: 'Approved',
    aiExtractedData: {
      customerName: 'Bina Perkasa Sdn Bhd',
      projectName: 'Projek Lebuh Raya MRR2',
      caseType: 'Bond Request',
      amount: 'RM 250,000.00',
      expiryDate: '2027-01-31',
      notes: 'Performance bond for MRR2 road construction. Insurer: Allianz. Effective 1 Feb 2026.',
    },
  },
  {
    id: 'file2',
    caseId: 'case1',
    fileName: 'SSM_Certificate_BinaPerkasa.pdf',
    fileSize: 485000,
    fileType: 'PDF',
    documentType: 'SSM',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-01-12T10:15:00Z',
    aiScanned: false,
    aiStatus: 'Not Scanned',
    aiExtractedData: null,
  },
  {
    id: 'file3',
    caseId: 'case4',
    fileName: 'Audited_Accounts_2025.pdf',
    fileSize: 3200000,
    fileType: 'PDF',
    documentType: 'Financial Statement',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-05-03T09:30:00Z',
    aiScanned: false,
    aiStatus: 'Not Scanned',
    aiExtractedData: null,
  },
]

// ─── Activity Logs ────────────────────────────────────────────────────────────

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log1',
    action: 'Case created',
    user: 'Ahmad Farid',
    target: 'Performance Bond — Projek Lebuh Raya MRR2',
    timestamp: '2026-01-10T08:00:00Z',
  },
  {
    id: 'log2',
    action: 'File uploaded',
    user: 'Ahmad Farid',
    target: 'Project_Contract_MRR2.pdf',
    timestamp: '2026-01-12T10:00:00Z',
  },
  {
    id: 'log3',
    action: 'AI scan approved',
    user: 'Ahmad Farid',
    target: 'Project_Contract_MRR2.pdf',
    timestamp: '2026-01-12T10:05:00Z',
  },
  {
    id: 'log4',
    action: 'Case status updated',
    user: 'Nurul Ain',
    target: 'Customs Bond — Annual Renewal 2026 → Submitted',
    timestamp: '2026-03-14T09:30:00Z',
  },
  {
    id: 'log5',
    action: 'Follow-up added',
    user: 'David Lim',
    target: 'Send quotation comparison to client for review',
    timestamp: '2026-05-10T10:00:00Z',
  },
  {
    id: 'log6',
    action: 'Note added',
    user: 'Ahmad Farid',
    target: 'Advance Payment Bond — Phase 3 Construction',
    timestamp: '2026-05-03T09:00:00Z',
  },
]

// ─── Editable Settings ────────────────────────────────────────────────────────

export const mockSettingsCaseTypes: SettingsItem[] = [
  { id: 'sct1', name: 'Bond Request', isActive: true },
  { id: 'sct2', name: 'Insurance Request', isActive: true },
  { id: 'sct3', name: 'Policy Issuance', isActive: true },
  { id: 'sct4', name: 'Renewal', isActive: true },
  { id: 'sct5', name: 'Endorsement', isActive: true },
  { id: 'sct6', name: 'Claim', isActive: true },
  { id: 'sct7', name: 'Servicing Request', isActive: true },
  { id: 'sct8', name: 'Quotation Request', isActive: true },
  { id: 'sct9', name: 'Other', isActive: true },
]

export const mockSettingsIndustries: SettingsItem[] = [
  { id: 'si1', name: 'Construction', isActive: true },
  { id: 'si2', name: 'Manufacturing', isActive: true },
  { id: 'si3', name: 'Trading', isActive: true },
  { id: 'si4', name: 'Retail', isActive: true },
  { id: 'si5', name: 'Services', isActive: true },
  { id: 'si6', name: 'Technology', isActive: true },
  { id: 'si7', name: 'Healthcare', isActive: true },
  { id: 'si8', name: 'Education', isActive: true },
  { id: 'si9', name: 'Transportation', isActive: true },
  { id: 'si10', name: 'Other', isActive: true },
]

export const mockSettingsContactTypes: SettingsItem[] = [
  { id: 'sco1', name: 'Owner', isActive: true },
  { id: 'sco2', name: 'Director', isActive: true },
  { id: 'sco3', name: 'Manager', isActive: true },
  { id: 'sco4', name: 'Finance', isActive: true },
  { id: 'sco5', name: 'Operations', isActive: true },
  { id: 'sco6', name: 'Worker', isActive: true },
  { id: 'sco7', name: 'Referral', isActive: true },
  { id: 'sco8', name: 'Introducer', isActive: true },
  { id: 'sco9', name: 'Other', isActive: true },
]

export const mockSettingsFollowUpCategories: SettingsItem[] = [
  { id: 'sfu1', name: 'Client Follow-Up', isActive: true },
  { id: 'sfu2', name: 'Insurer Follow-Up', isActive: true },
  { id: 'sfu3', name: 'Renewal Reminder', isActive: true },
  { id: 'sfu4', name: 'Documentation', isActive: true },
  { id: 'sfu5', name: 'Internal', isActive: true },
  { id: 'sfu6', name: 'Payment', isActive: true },
  { id: 'sfu7', name: 'Other', isActive: true },
]

export const mockSettingsDocumentTypes: SettingsItem[] = [
  { id: 'sdt1', name: 'Contract', isActive: true },
  { id: 'sdt2', name: 'Financial Statement', isActive: true },
  { id: 'sdt3', name: 'SSM', isActive: true },
  { id: 'sdt4', name: 'Application Form', isActive: true },
  { id: 'sdt5', name: 'Quotation', isActive: true },
  { id: 'sdt6', name: 'Supporting Document', isActive: true },
  { id: 'sdt7', name: 'Other', isActive: true },
]
