import type {
  Customer, Contact, Case, CaseNote, FollowUp, PicUser, User,
  CaseFile, ActivityLog, SettingsItem, WorkflowTemplate,
} from './types'

export const mockPics: PicUser[] = [
  { id: 'pic1', name: 'Ahmad Farid', email: 'ahmad@bondinsurance.com' },
  { id: 'pic2', name: 'Nurul Ain', email: 'nurul@bondinsurance.com' },
  { id: 'pic3', name: 'David Lim', email: 'david@bondinsurance.com' },
]

export const mockCustomers: Customer[] = [
  {
    id: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    companyRegistrationNo: '199801012345',
    industry: 'Construction',
    mainPhone: '03-12345678',
    mainEmail: 'admin@binaperkasa.com',
    notes: 'Key client. Handles large government construction projects.',
    createdAt: '2025-06-10T08:00:00Z',
  },
  {
    id: 'cust2',
    customerName: 'Maju Jaya Trading Sdn Bhd',
    companyRegistrationNo: '200201054321',
    industry: 'Trading',
    mainPhone: '03-78912345',
    mainEmail: 'admin@majujaya.com',
    notes: 'Import and export trader. Requires customs bonds every year.',
    createdAt: '2025-08-20T09:00:00Z',
  },
  {
    id: 'cust3',
    customerName: 'Teknologi Canggih Sdn Bhd',
    companyRegistrationNo: '201501098765',
    industry: 'Technology',
    mainPhone: '03-23456789',
    mainEmail: 'admin@tekcanggih.com',
    notes: 'IT company. Occasional bonds for government tenders.',
    createdAt: '2025-10-05T10:00:00Z',
  },
  {
    id: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    companyRegistrationNo: '199901076543',
    industry: 'Construction',
    mainPhone: '03-98765432',
    mainEmail: 'admin@mutiarapermai.com',
    notes: 'Property developer. Multiple bonds required per project.',
    createdAt: '2025-11-10T11:00:00Z',
  },
  {
    id: 'cust5',
    customerName: 'Prisma Logistics Sdn Bhd',
    companyRegistrationNo: '201801033210',
    industry: 'Transportation',
    mainPhone: '03-55512345',
    mainEmail: 'admin@prismalogistics.com',
    notes: 'Freight forwarding. Needs customs bonds and workers compensation.',
    createdAt: '2026-01-15T09:00:00Z',
  },
]

export const mockContacts: Contact[] = [
  // Bina Perkasa (cust1)
  {
    id: 'con1', customerId: 'cust1', contactName: 'Razif Harun',
    role: 'Managing Director', phone: '012-3456789', email: 'razif@binaperkasa.com',
    contactType: 'Director', isPrimary: true,
  },
  {
    id: 'con2', customerId: 'cust1', contactName: 'Faridah Zain',
    role: 'Finance Manager', phone: '012-3456780', email: 'faridah@binaperkasa.com',
    contactType: 'Finance', isPrimary: false,
  },
  // Maju Jaya (cust2)
  {
    id: 'con3', customerId: 'cust2', contactName: 'Lee Chee Keong',
    role: 'Owner', phone: '016-7891234', email: 'cheekeong@majujaya.com',
    contactType: 'Owner', isPrimary: true,
  },
  {
    id: 'con4', customerId: 'cust2', contactName: 'Michelle Tan',
    role: 'Operations', phone: '016-7891235', email: 'michelle@majujaya.com',
    contactType: 'Operations', isPrimary: false,
  },
  // Teknologi Canggih (cust3)
  {
    id: 'con5', customerId: 'cust3', contactName: 'Sarah Tan',
    role: 'Operations Manager', phone: '011-23456789', email: 'sarah@tekcanggih.com',
    contactType: 'Manager', isPrimary: true,
  },
  {
    id: 'con6', customerId: 'cust3', contactName: 'James Ng',
    role: 'IT Director', phone: '011-23456780', email: 'james@tekcanggih.com',
    contactType: 'Director', isPrimary: false,
  },
  // Mutiara Permai (cust4)
  {
    id: 'con7', customerId: 'cust4', contactName: 'Hafizah Mohd',
    role: 'Director', phone: '019-9876543', email: 'hafizah@mutiarapermai.com',
    contactType: 'Director', isPrimary: true,
  },
  {
    id: 'con8', customerId: 'cust4', contactName: 'Azrul Nizam',
    role: 'Project Manager', phone: '019-9876544', email: 'azrul@mutiarapermai.com',
    contactType: 'Manager', isPrimary: false,
  },
  // Prisma Logistics (cust5)
  {
    id: 'con9', customerId: 'cust5', contactName: 'Kevin Wong',
    role: 'Managing Director', phone: '017-5551234', email: 'kevin@prismalogistics.com',
    contactType: 'Director', isPrimary: true,
  },
]

export const mockCases: Case[] = [
  {
    id: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseType: 'Bond Request',
    amount: 250000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-28T10:00:00Z',
    currentStatus: 'Confirmed',
    currentWorkflowStepId: 'ws6',
    result: 'Won',
    closingRemarks: 'Bond issued by Allianz. Effective 1 Feb 2026.',
    finalInsurer: 'Allianz',
  },
  {
    id: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    customerId: 'cust2',
    customerName: 'Maju Jaya Trading Sdn Bhd',
    caseType: 'Renewal',
    amount: 80000,
    personInCharge: 'Nurul Ain',
    createdAt: '2026-03-14T09:00:00Z',
    updatedAt: '2026-03-28T10:00:00Z',
    currentStatus: 'Submitted',
    currentWorkflowStepId: 'ws22',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    customerId: 'cust3',
    customerName: 'Teknologi Canggih Sdn Bhd',
    caseType: 'Bond Request',
    amount: 120000,
    personInCharge: 'David Lim',
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-04-10T11:00:00Z',
    currentStatus: 'Quoted',
    currentWorkflowStepId: 'ws4',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseType: 'Bond Request',
    amount: 500000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2026-04-20T08:00:00Z',
    updatedAt: '2026-05-03T09:00:00Z',
    currentStatus: 'Waiting Documents',
    currentWorkflowStepId: 'ws1',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case5',
    caseTitle: 'Fidelity Guarantee — Finance Department',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseType: 'Insurance Request',
    amount: 50000,
    personInCharge: 'Nurul Ain',
    createdAt: '2026-04-28T09:00:00Z',
    updatedAt: '2026-04-28T09:00:00Z',
    currentStatus: 'New',
    currentWorkflowStepId: 'ws10',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case6',
    caseTitle: 'Immigration Bond — Foreign Workers Batch B',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseType: 'Bond Request',
    amount: 35000,
    personInCharge: 'David Lim',
    createdAt: '2026-05-02T10:00:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
    currentStatus: 'Sent to Customer',
    currentWorkflowStepId: 'ws5',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case7',
    caseTitle: 'Workers Compensation — Freight Team',
    customerId: 'cust5',
    customerName: 'Prisma Logistics Sdn Bhd',
    caseType: 'Insurance Request',
    amount: 15000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2026-05-08T09:00:00Z',
    updatedAt: '2026-05-08T09:00:00Z',
    currentStatus: 'New',
    currentWorkflowStepId: 'ws10',
    result: '',
    closingRemarks: '',
  },
  {
    id: 'case8',
    caseTitle: 'Performance Bond — Coastal Highway Phase 1',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseType: 'Bond Request',
    amount: 380000,
    personInCharge: 'Ahmad Farid',
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2025-12-15T10:00:00Z',
    currentStatus: 'Closed',
    currentWorkflowStepId: 'ws8',
    result: 'Lost',
    closingRemarks: 'Client went with another agent offering a lower premium.',
    lossReason: 'Price — competitor offered lower premium',
    closedAt: '2025-12-15T10:00:00Z',
  },
]

export const mockCaseNotes: CaseNote[] = [
  {
    id: 'note1',
    caseId: 'case1',
    content: 'Client confirmed they want Allianz. Proceed with bond issuance.',
    createdAt: '2026-01-22T14:00:00Z',
    createdBy: 'Ahmad Farid',
  },
  {
    id: 'note2',
    caseId: 'case1',
    content: 'Bond issued. Original document couriered to client office.',
    createdAt: '2026-02-01T11:00:00Z',
    createdBy: 'Ahmad Farid',
  },
  {
    id: 'note3',
    caseId: 'case2',
    content: 'Submitted to Customs department. Reference: CUST-2026-00412.',
    createdAt: '2026-03-28T10:30:00Z',
    createdBy: 'Nurul Ain',
  },
  {
    id: 'note4',
    caseId: 'case3',
    content: 'Quotations from 3 insurers sent to client. Waiting for their decision.',
    createdAt: '2026-04-10T11:00:00Z',
    createdBy: 'David Lim',
  },
  {
    id: 'note5',
    caseId: 'case4',
    content: 'Client has not submitted audited accounts yet. Need to follow up.',
    createdAt: '2026-05-03T09:00:00Z',
    createdBy: 'Ahmad Farid',
  },
]

export const mockFollowUps: FollowUp[] = [
  {
    id: 'fu1',
    title: 'Call client to check on customs bond approval',
    customerId: 'cust2',
    customerName: 'Maju Jaya Trading Sdn Bhd',
    caseId: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    personInCharge: 'Nurul Ain',
    dueDate: '2026-05-10',
    status: 'Open',
    createdAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'fu2',
    title: 'Collect audited accounts and company profile',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseId: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    personInCharge: 'Ahmad Farid',
    dueDate: '2026-05-05',
    status: 'Done',
    createdAt: '2026-04-28T09:00:00Z',
  },
  {
    id: 'fu3',
    title: 'Send quotation comparison to client for review',
    customerId: 'cust3',
    customerName: 'Teknologi Canggih Sdn Bhd',
    caseId: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    personInCharge: 'David Lim',
    dueDate: '2026-05-20',
    status: 'Open',
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'fu4',
    title: 'Remind client about workers list for immigration bond',
    customerId: 'cust4',
    customerName: 'Mutiara Permai Sdn Bhd',
    caseId: 'case6',
    caseTitle: 'Immigration Bond — Foreign Workers Batch B',
    personInCharge: 'David Lim',
    dueDate: '2026-05-16',
    status: 'Open',
    createdAt: '2026-05-13T10:00:00Z',
  },
  {
    id: 'fu5',
    title: 'Prepare fidelity guarantee proposal document',
    customerId: 'cust1',
    customerName: 'Bina Perkasa Sdn Bhd',
    caseId: 'case5',
    caseTitle: 'Fidelity Guarantee — Finance Department',
    personInCharge: 'Nurul Ain',
    dueDate: '2026-05-22',
    status: 'Open',
    createdAt: '2026-05-14T09:00:00Z',
  },
  {
    id: 'fu6',
    title: 'Submit workers compensation proposal to insurer',
    customerId: 'cust5',
    customerName: 'Prisma Logistics Sdn Bhd',
    caseId: 'case7',
    caseTitle: 'Workers Compensation — Freight Team',
    personInCharge: 'Ahmad Farid',
    dueDate: '2026-05-30',
    status: 'Open',
    createdAt: '2026-05-08T11:00:00Z',
  },
]

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'usr1',
    fullName: 'Ahmad Farid',
    email: 'ahmad@bondinsurance.com',
    password: 'password123',
    role: 'Admin',
    status: 'Active',
    createdAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'usr2',
    fullName: 'Nurul Ain',
    email: 'nurul@bondinsurance.com',
    password: 'password123',
    role: 'Staff',
    status: 'Active',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'usr3',
    fullName: 'David Lim',
    email: 'david@bondinsurance.com',
    password: 'password123',
    role: 'Staff',
    status: 'Active',
    createdAt: '2024-02-01T08:00:00Z',
  },
]

// ─── Case Files ───────────────────────────────────────────────────────────────

export const mockCaseFiles: CaseFile[] = [
  {
    id: 'file1',
    caseId: 'case1',
    fileName: 'Project_Contract_MRR2.pdf',
    fileSize: 2150000,
    fileType: 'PDF',
    documentType: 'Contract / Award Letter',
    requiredDocumentId: 'rd4',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-01-12T10:00:00Z',
    aiScanned: true,
    aiStatus: 'Approved',
    aiExtractedData: {
      customerName: 'Bina Perkasa Sdn Bhd',
      projectName: 'Projek Lebuh Raya MRR2',
      caseType: 'Bond Request',
      amount: 'RM 250,000.00',
      expiryDate: '2027-01-31',
      notes: 'Performance bond for MRR2 road construction. Insurer: Allianz. Effective 1 Feb 2026.',
    },
  },
  {
    id: 'file2',
    caseId: 'case1',
    fileName: 'SSM_Certificate_BinaPerkasa.pdf',
    fileSize: 485000,
    fileType: 'PDF',
    documentType: 'SSM Certificate',
    requiredDocumentId: 'rd2',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-01-12T10:15:00Z',
    aiScanned: false,
    aiStatus: 'Not Scanned',
    aiExtractedData: null,
  },
  {
    id: 'file3',
    caseId: 'case1',
    fileName: 'CompanyProfile_BinaPerkasa.pdf',
    fileSize: 1200000,
    fileType: 'PDF',
    documentType: 'Company Profile',
    requiredDocumentId: 'rd1',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-01-12T10:20:00Z',
    aiScanned: false,
    aiStatus: 'Not Scanned',
    aiExtractedData: null,
  },
  {
    id: 'file4',
    caseId: 'case4',
    fileName: 'Audited_Accounts_2025.pdf',
    fileSize: 3200000,
    fileType: 'PDF',
    documentType: 'Financial Statement',
    requiredDocumentId: 'rd3',
    uploadedBy: 'Ahmad Farid',
    uploadedAt: '2026-05-03T09:30:00Z',
    aiScanned: false,
    aiStatus: 'Not Scanned',
    aiExtractedData: null,
  },
  {
    id: 'file5',
    caseId: 'case3',
    fileName: 'ApplicationForm_MyGovIT.pdf',
    fileSize: 520000,
    fileType: 'PDF',
    documentType: 'Application Form',
    requiredDocumentId: 'rd5',
    uploadedBy: 'David Lim',
    uploadedAt: '2026-04-03T11:00:00Z',
    aiScanned: false,
    aiStatus: 'Not Scanned',
    aiExtractedData: null,
  },
]

// ─── Activity Logs ────────────────────────────────────────────────────────────

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log1',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'CASE_CREATED',
    title: 'Case created',
    description: 'New bond request case opened',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-10T08:00:00Z',
  },
  {
    id: 'log2',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'STATUS_CHANGED',
    title: 'Status changed',
    oldValue: 'New',
    newValue: 'Waiting Documents',
    description: 'Status changed from New to Waiting Documents',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-10T08:05:00Z',
  },
  {
    id: 'log3',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'DOCUMENT_UPLOADED',
    title: 'Document uploaded',
    newValue: 'Company Profile',
    description: 'CompanyProfile_BinaPerkasa.pdf uploaded',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-12T10:00:00Z',
  },
  {
    id: 'log4',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'DOCUMENT_UPLOADED',
    title: 'Document uploaded',
    newValue: 'Contract / Award Letter',
    description: 'Project_Contract_MRR2.pdf uploaded',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-12T10:02:00Z',
  },
  {
    id: 'log5',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'AI_SCAN_STARTED',
    title: 'AI scan started',
    description: 'AI scanning Project_Contract_MRR2.pdf',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-12T10:03:00Z',
  },
  {
    id: 'log6',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'AI_EXTRACTION_APPROVED',
    title: 'AI extraction approved',
    description: 'Extracted data from Project_Contract_MRR2.pdf approved',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-12T10:10:00Z',
  },
  {
    id: 'log7',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'WORKFLOW_STEP_CHANGED',
    title: 'Workflow step advanced',
    oldValue: 'Collect Documents',
    newValue: 'Submit to Insurer',
    description: 'Moved from Collect Documents to Submit to Insurer',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-14T09:00:00Z',
  },
  {
    id: 'log8',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'STATUS_CHANGED',
    title: 'Status changed',
    oldValue: 'Waiting Documents',
    newValue: 'Submitted',
    description: 'Status changed from Waiting Documents to Submitted',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-14T09:05:00Z',
  },
  {
    id: 'log9',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'FOLLOW_UP_CREATED',
    title: 'Follow-up created',
    description: 'Confirm payment receipt from client',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-22T09:00:00Z',
  },
  {
    id: 'log10',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'NOTE_ADDED',
    title: 'Note added',
    description: 'Client confirmed they want Allianz. Proceed with bond issuance.',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-22T14:00:00Z',
  },
  {
    id: 'log11',
    caseId: 'case1',
    caseTitle: 'Performance Bond — Projek Lebuh Raya MRR2',
    actionType: 'RESULT_SET',
    title: 'Case result set',
    oldValue: '',
    newValue: 'Won',
    description: 'Case marked as Won. Bond issued by Allianz.',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-01-28T10:00:00Z',
  },
  {
    id: 'log12',
    caseId: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    actionType: 'CASE_CREATED',
    title: 'Case created',
    description: 'New renewal case opened',
    changedBy: 'Nurul Ain',
    timestamp: '2026-03-14T09:00:00Z',
  },
  {
    id: 'log13',
    caseId: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    actionType: 'STATUS_CHANGED',
    title: 'Status changed',
    oldValue: 'New',
    newValue: 'Submitted',
    description: 'Status changed from New to Submitted',
    changedBy: 'Nurul Ain',
    timestamp: '2026-03-28T10:00:00Z',
  },
  {
    id: 'log14',
    caseId: 'case2',
    caseTitle: 'Customs Bond — Annual Renewal 2026',
    actionType: 'NOTE_ADDED',
    title: 'Note added',
    description: 'Submitted to Customs department. Reference: CUST-2026-00412.',
    changedBy: 'Nurul Ain',
    timestamp: '2026-03-28T10:30:00Z',
  },
  {
    id: 'log15',
    caseId: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    actionType: 'CASE_CREATED',
    title: 'Case created',
    description: 'New bond request case opened',
    changedBy: 'David Lim',
    timestamp: '2026-04-01T10:00:00Z',
  },
  {
    id: 'log16',
    caseId: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    actionType: 'DOCUMENT_UPLOADED',
    title: 'Document uploaded',
    newValue: 'Application Form',
    description: 'ApplicationForm_MyGovIT.pdf uploaded',
    changedBy: 'David Lim',
    timestamp: '2026-04-03T11:00:00Z',
  },
  {
    id: 'log17',
    caseId: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    actionType: 'STATUS_CHANGED',
    title: 'Status changed',
    oldValue: 'Submitted',
    newValue: 'Quoted',
    description: 'Status changed from Submitted to Quoted',
    changedBy: 'David Lim',
    timestamp: '2026-04-10T11:00:00Z',
  },
  {
    id: 'log18',
    caseId: 'case3',
    caseTitle: 'Performance Bond — MyGovIT System Integration',
    actionType: 'FOLLOW_UP_CREATED',
    title: 'Follow-up created',
    description: 'Send quotation comparison to client for review',
    changedBy: 'David Lim',
    timestamp: '2026-05-10T10:00:00Z',
  },
  {
    id: 'log19',
    caseId: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    actionType: 'CASE_CREATED',
    title: 'Case created',
    description: 'New bond request case opened',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-04-20T08:00:00Z',
  },
  {
    id: 'log20',
    caseId: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    actionType: 'DOCUMENT_UPLOADED',
    title: 'Document uploaded',
    newValue: 'Financial Statement',
    description: 'Audited_Accounts_2025.pdf uploaded',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-05-03T09:30:00Z',
  },
  {
    id: 'log21',
    caseId: 'case4',
    caseTitle: 'Advance Payment Bond — Phase 3 Construction',
    actionType: 'NOTE_ADDED',
    title: 'Note added',
    description: 'Client has not submitted audited accounts yet. Need to follow up.',
    changedBy: 'Ahmad Farid',
    timestamp: '2026-05-03T09:00:00Z',
  },
]

// ─── Editable Settings ────────────────────────────────────────────────────────

export const mockSettingsCaseTypes: SettingsItem[] = [
  { id: 'sct1', name: 'Bond Request', isActive: true },
  { id: 'sct2', name: 'Insurance Request', isActive: true },
  { id: 'sct3', name: 'Policy Issuance', isActive: true },
  { id: 'sct4', name: 'Renewal', isActive: true },
  { id: 'sct5', name: 'Endorsement', isActive: true },
  { id: 'sct6', name: 'Claim', isActive: true },
  { id: 'sct7', name: 'Servicing Request', isActive: true },
  { id: 'sct8', name: 'Quotation Request', isActive: true },
  { id: 'sct9', name: 'Other', isActive: true },
]

export const mockSettingsIndustries: SettingsItem[] = [
  { id: 'si1', name: 'Construction', isActive: true },
  { id: 'si2', name: 'Manufacturing', isActive: true },
  { id: 'si3', name: 'Trading', isActive: true },
  { id: 'si4', name: 'Retail', isActive: true },
  { id: 'si5', name: 'Services', isActive: true },
  { id: 'si6', name: 'Technology', isActive: true },
  { id: 'si7', name: 'Healthcare', isActive: true },
  { id: 'si8', name: 'Education', isActive: true },
  { id: 'si9', name: 'Transportation', isActive: true },
  { id: 'si10', name: 'Other', isActive: true },
]

export const mockSettingsContactTypes: SettingsItem[] = [
  { id: 'sco1', name: 'Owner', isActive: true },
  { id: 'sco2', name: 'Director', isActive: true },
  { id: 'sco3', name: 'Manager', isActive: true },
  { id: 'sco4', name: 'Finance', isActive: true },
  { id: 'sco5', name: 'Operations', isActive: true },
  { id: 'sco6', name: 'Worker', isActive: true },
  { id: 'sco7', name: 'Referral', isActive: true },
  { id: 'sco8', name: 'Introducer', isActive: true },
  { id: 'sco9', name: 'Other', isActive: true },
]

export const mockSettingsFollowUpCategories: SettingsItem[] = [
  { id: 'sfu1', name: 'Client Follow-Up', isActive: true },
  { id: 'sfu2', name: 'Insurer Follow-Up', isActive: true },
  { id: 'sfu3', name: 'Renewal Reminder', isActive: true },
  { id: 'sfu4', name: 'Documentation', isActive: true },
  { id: 'sfu5', name: 'Internal', isActive: true },
  { id: 'sfu6', name: 'Payment', isActive: true },
  { id: 'sfu7', name: 'Other', isActive: true },
]

export const mockSettingsDocumentTypes: SettingsItem[] = [
  { id: 'sdt1', name: 'Contract / Award Letter', isActive: true },
  { id: 'sdt2', name: 'Financial Statement', isActive: true },
  { id: 'sdt3', name: 'SSM Certificate', isActive: true },
  { id: 'sdt4', name: 'Application Form', isActive: true },
  { id: 'sdt5', name: 'Quotation', isActive: true },
  { id: 'sdt6', name: 'Company Profile', isActive: true },
  { id: 'sdt7', name: 'Bank Statement', isActive: true },
  { id: 'sdt8', name: 'Identity Card', isActive: true },
  { id: 'sdt9', name: 'Previous Policy / Bond', isActive: true },
  { id: 'sdt10', name: 'Supporting Document', isActive: true },
  { id: 'sdt11', name: 'Other', isActive: true },
]

// ─── Workflow Templates ───────────────────────────────────────────────────────

export const mockWorkflowTemplates: WorkflowTemplate[] = [
  {
    id: 'wt1',
    caseType: 'Bond Request',
    description: 'Standard bond request process for performance, advance payment, and other bonds.',
    isActive: true,
    requiredDocuments: [
      {
        id: 'rd1', caseTypeId: 'wt1', name: 'Company Profile',
        description: 'Company background and business overview', required: true,
        acceptedFileTypes: ['PDF', 'DOCX'], isActive: true,
      },
      {
        id: 'rd2', caseTypeId: 'wt1', name: 'SSM Certificate',
        description: 'Companies Commission of Malaysia registration certificate', required: true,
        acceptedFileTypes: ['PDF', 'JPG', 'PNG'], isActive: true,
      },
      {
        id: 'rd3', caseTypeId: 'wt1', name: 'Financial Statement',
        description: 'Latest audited financial accounts (minimum 2 years)', required: true,
        acceptedFileTypes: ['PDF', 'XLSX'], isActive: true,
      },
      {
        id: 'rd4', caseTypeId: 'wt1', name: 'Contract / Award Letter',
        description: 'Contract or letter of award from the project owner', required: true,
        acceptedFileTypes: ['PDF', 'DOCX'], isActive: true,
        aiPrompt: `This is a Surat Setuju Terima (SST) / Letter of Award / Contract Acceptance from a Malaysian government agency or project owner.

Extract the following:
- customerName: The CONTRACTOR's full company name and registration number (the party AWARDED the contract — look for "Syarikat", "Sdn. Bhd.", "Enterprise" — NOT the government agency)
- projectName: The full description of works / Skop Kerja / Perihal Kerja as stated in the document
- caseType: The type of bond or security deposit required (e.g. "Performance Bond", "Bon Pelaksanaan", "Wang Jaminan")
- amount: The CONTRACT VALUE / Harga Kontrak / Harga Sebutharga (the total awarded contract sum in RM)
- bondValue: The bond/deposit amount (look for "Bon Pelaksanaan", "deposit", "jaminan" — typically 5% of contract value)
- expiryDate: Contract completion date / Tarikh Siap or end of Defect Liability Period (DLP)
- notes: All reference numbers — SST no., Tender no. / No. Sebutharga, issuing government department or agency name`,
      },
      {
        id: 'rd5', caseTypeId: 'wt1', name: 'Application Form',
        description: 'Completed bond application form', required: true,
        acceptedFileTypes: ['PDF', 'DOCX'], isActive: true,
      },
      {
        id: 'rd6', caseTypeId: 'wt1', name: 'Bank Statement',
        description: 'Latest 3 months company bank statement', required: false,
        acceptedFileTypes: ['PDF'], isActive: true,
      },
      {
        id: 'rd7', caseTypeId: 'wt1', name: "Director's IC",
        description: "Copy of director's MyKad (front and back)", required: false,
        acceptedFileTypes: ['PDF', 'JPG', 'PNG'], isActive: true,
      },
    ],
    workflowSteps: [
      {
        id: 'ws1', caseTypeId: 'wt1', name: 'Collect Documents', order: 1,
        description: 'Gather all required documents from the client',
        requireDocumentsComplete: false,
        defaultFollowUpSuggestion: 'Request outstanding documents from client',
        isActive: true,
      },
      {
        id: 'ws2', caseTypeId: 'wt1', name: 'Review Documents', order: 2,
        description: 'Review submitted documents for completeness and accuracy',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Review and verify client documents',
        isActive: true,
      },
      {
        id: 'ws3', caseTypeId: 'wt1', name: 'Submit to Insurer', order: 3,
        description: 'Submit completed application and all documents to insurer',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Follow up with insurer on submission status',
        isActive: true,
      },
      {
        id: 'ws4', caseTypeId: 'wt1', name: 'Receive Quotation', order: 4,
        description: 'Receive and review bond quotation from insurer',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Chase insurer for quotation',
        isActive: true,
      },
      {
        id: 'ws5', caseTypeId: 'wt1', name: 'Send to Customer', order: 5,
        description: 'Present quotation and terms to client for review',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Follow up with client on quotation decision',
        isActive: true,
      },
      {
        id: 'ws6', caseTypeId: 'wt1', name: 'Confirm Acceptance', order: 6,
        description: 'Client confirms acceptance and pays premium',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Confirm payment receipt from client',
        isActive: true,
      },
      {
        id: 'ws7', caseTypeId: 'wt1', name: 'Issue Bond', order: 7,
        description: 'Insurer issues bond certificate and delivers to client',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Arrange bond certificate delivery to client',
        isActive: true,
      },
      {
        id: 'ws8', caseTypeId: 'wt1', name: 'Close Case', order: 8,
        description: 'Case is complete. Bond issued and delivered to client.',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: '',
        isActive: true,
      },
    ],
  },
  {
    id: 'wt2',
    caseType: 'Insurance Request',
    description: 'Standard insurance application and issuance process.',
    isActive: true,
    requiredDocuments: [
      {
        id: 'rd10', caseTypeId: 'wt2', name: 'Application Form',
        description: 'Completed insurance application form', required: true,
        acceptedFileTypes: ['PDF', 'DOCX'], isActive: true,
      },
      {
        id: 'rd11', caseTypeId: 'wt2', name: 'Identity Card',
        description: 'Copy of IC or passport (directors/owners)', required: true,
        acceptedFileTypes: ['PDF', 'JPG', 'PNG'], isActive: true,
      },
      {
        id: 'rd12', caseTypeId: 'wt2', name: 'Supporting Documents',
        description: 'Additional documents specific to the policy type', required: false,
        acceptedFileTypes: ['PDF', 'DOCX', 'JPG'], isActive: true,
      },
    ],
    workflowSteps: [
      {
        id: 'ws10', caseTypeId: 'wt2', name: 'Collect Requirements', order: 1,
        description: 'Understand client needs and collect required documents',
        requireDocumentsComplete: false,
        defaultFollowUpSuggestion: 'Contact client for insurance requirements',
        isActive: true,
      },
      {
        id: 'ws11', caseTypeId: 'wt2', name: 'Get Quotation', order: 2,
        description: 'Obtain quotations from suitable insurers',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Request quotation from insurer',
        isActive: true,
      },
      {
        id: 'ws12', caseTypeId: 'wt2', name: 'Present to Customer', order: 3,
        description: 'Present and explain quotation options to client',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Follow up with client on insurance proposal',
        isActive: true,
      },
      {
        id: 'ws13', caseTypeId: 'wt2', name: 'Confirm Policy', order: 4,
        description: 'Client confirms chosen policy and authorizes payment',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Confirm policy acceptance and collect payment',
        isActive: true,
      },
      {
        id: 'ws14', caseTypeId: 'wt2', name: 'Issue Certificate', order: 5,
        description: 'Insurer issues policy certificate to client',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Deliver policy documents to client',
        isActive: true,
      },
      {
        id: 'ws15', caseTypeId: 'wt2', name: 'Close Case', order: 6,
        description: 'Policy issued. Case complete.',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: '',
        isActive: true,
      },
    ],
  },
  {
    id: 'wt3',
    caseType: 'Renewal',
    description: 'Annual renewal process for existing bonds and policies.',
    isActive: true,
    requiredDocuments: [
      {
        id: 'rd20', caseTypeId: 'wt3', name: 'Previous Policy / Bond',
        description: 'Copy of existing policy or bond certificate for renewal', required: true,
        acceptedFileTypes: ['PDF', 'JPG'], isActive: true,
        aiPrompt: `This is a performance bond certificate, bank guarantee, or insurance policy document for renewal purposes.

Extract the following:
- customerName: The INSURED / PRINCIPAL company name and registration number
- projectName: The project description or risk location as stated in the certificate
- caseType: Bond or insurance type (e.g. "Performance Bond", "Contractor All Risk", "Public Liability", "Workmen Compensation")
- amount: Contract value or sum insured (if stated)
- bondValue: The guaranteed / insured amount — the principal sum of the bond or policy
- expiryDate: The bond or policy EXPIRY DATE / Tarikh Tamat / validity end date
- notes: Certificate or policy number, issuing insurer or bank name`,
      },
      {
        id: 'rd21', caseTypeId: 'wt3', name: 'Updated Bank Statement',
        description: 'Latest 3 months bank statement if required by insurer', required: false,
        acceptedFileTypes: ['PDF'], isActive: true,
      },
    ],
    workflowSteps: [
      {
        id: 'ws20', caseTypeId: 'wt3', name: 'Review Expiry', order: 1,
        description: 'Review expiry date and initiate renewal process with client',
        requireDocumentsComplete: false,
        defaultFollowUpSuggestion: 'Notify client of upcoming renewal',
        isActive: true,
      },
      {
        id: 'ws21', caseTypeId: 'wt3', name: 'Get Renewal Quote', order: 2,
        description: 'Obtain renewal quotation from current or alternative insurer',
        requireDocumentsComplete: false,
        defaultFollowUpSuggestion: 'Request renewal quotation from insurer',
        isActive: true,
      },
      {
        id: 'ws22', caseTypeId: 'wt3', name: 'Send to Customer', order: 3,
        description: 'Present renewal quotation to client for approval',
        requireDocumentsComplete: false,
        defaultFollowUpSuggestion: 'Follow up with client on renewal decision',
        isActive: true,
      },
      {
        id: 'ws23', caseTypeId: 'wt3', name: 'Confirm Renewal', order: 4,
        description: 'Client approves renewal and authorizes payment',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Confirm renewal approval and collect payment',
        isActive: true,
      },
      {
        id: 'ws24', caseTypeId: 'wt3', name: 'Process Renewal', order: 5,
        description: 'Submit renewal to insurer and obtain new certificate',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: 'Deliver renewed policy documents to client',
        isActive: true,
      },
      {
        id: 'ws25', caseTypeId: 'wt3', name: 'Close Case', order: 6,
        description: 'Renewal complete. New certificate issued to client.',
        requireDocumentsComplete: true,
        defaultFollowUpSuggestion: '',
        isActive: true,
      },
    ],
  },
]
